import { SetupOverlays } from "@/components/overlays";
import "./global.css";
import { SetupCart } from "./setup-cart";
import { getCachedDB } from "@/lib/cached-db";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  async function prefetchCart() {
  // placeholder async fetch
  return true
}

  const cartPromise = await prefetchCart()
  return (
    <html lang="en">
      <body >
        <SetupCart cartPromise={cartPromise} />
        {children}
      </body>
    </html>
  );
}
