
import "./global.css";
import SetupCart from "../store/cart/cart-state";


export async function generateMetadata()  {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  }
};

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <body >
        <SetupCart />
        {children}
      </body>
    </html>
  );
}


