
import "./global.css";
import SetupCart from "./setup-cart";


export async function generateMetadata()  {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  }
};

export default async function RootLayout({ children }) {

  // const fetchCart = prefetchCart()

  return (
    <html lang="en">
      <body >
        <SetupCart />
        {children}
      </body>
    </html>
  );
}
